package diagnosis

import (
	"fmt"
	"sort"
	"strings"
)

// isAutoGeneratedServiceName returns true if a service name looks like an
// auto-generated UUID-derived name (e.g. dc-0012191e9cc8-00006-private).
// Heuristic: name is longer than 30 chars AND more than 50% of non-hyphen
// characters are hex digits [0-9a-f].
func isAutoGeneratedServiceName(name string) bool {
	if len(name) <= 30 {
		return false
	}
	lower := strings.ToLower(name)
	var total, hexCount int
	for _, ch := range lower {
		if ch == '-' {
			continue
		}
		total++
		if (ch >= '0' && ch <= '9') || (ch >= 'a' && ch <= 'f') {
			hexCount++
		}
	}
	if total == 0 {
		return false
	}
	return hexCount*2 > total // more than 50%
}

// NoEndpointsClassifier finds services that have a selector but no ready endpoints.
type NoEndpointsClassifier struct{}

func (NoEndpointsClassifier) Classify(results ScanResults) []Finding {
	var findings []Finding
	for _, s := range results.Services {
		if isAutoGeneratedServiceName(s.ServiceName) {
			continue
		}
		// Build a sorted "key=val,key=val" selector string.
		var parts []string
		for k, v := range s.Selector {
			parts = append(parts, fmt.Sprintf("%s=%s", k, v))
		}
		sort.Strings(parts)
		selectorStr := strings.Join(parts, ",")

		oneLiner := "no ready endpoints"

		findings = append(findings, Finding{
			Category:   CategoryNoEndpoints,
			Severity:   SeverityWarning,
			EnvName:    results.EnvName,
			ClusterCtx: results.ClusterCtx,
			Namespace:  s.Namespace,
			PodName:    s.ServiceName,
			OneLiner:   oneLiner,
			DetailFields: map[string]string{
				"selector": selectorStr,
			},
		})
	}
	return findings
}
