package diagnosis

import (
	"testing"

	"github.com/vishukamble/klarity/pkg/kube"
)

func TestIsAutoGeneratedServiceName(t *testing.T) {
	tests := []struct {
		name string
		want bool
	}{
		{"nginx", false},
		{"api-gateway", false},
		{"my-service-v2", false},
		// 30 chars but not hex-heavy
		{"my-very-long-but-normal-service", false},
		// UUID-derived: long + hex-heavy
		{"dc-0012191e9cc83edc388be8af45abca801555a7df-00006-private", true},
		{"3b9f2a1c4d8e0f6b7a5c9e2d1f3a7b4c8e-svc", true},
		// borderline: 33 chars, 32/33 are hex → auto-generated
		{"abcdef0123456789abcdef0123456789x", true},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			got := isAutoGeneratedServiceName(tt.name)
			if got != tt.want {
				t.Errorf("isAutoGeneratedServiceName(%q) = %v, want %v", tt.name, got, tt.want)
			}
		})
	}
}

func TestNoEndpoints_SkipsUUIDServices(t *testing.T) {
	results := ScanResults{
		Services: []kube.ServiceIssue{
			{
				Namespace:   "default",
				ServiceName: "dc-0012191e9cc83edc388be8af45abca801555a7df-00006-private",
				Selector:    map[string]string{"app": "something"},
			},
		},
	}
	c := NoEndpointsClassifier{}
	got := c.Classify(results)
	if len(got) != 0 {
		t.Errorf("expected UUID-named service to be skipped, got %d findings", len(got))
	}
}

func TestNoEndpoints_KeepsNormalServices(t *testing.T) {
	results := ScanResults{
		Services: []kube.ServiceIssue{
			{Namespace: "ns1", ServiceName: "nginx", Selector: map[string]string{"app": "nginx"}},
			{Namespace: "ns2", ServiceName: "api-gateway", Selector: map[string]string{"app": "api"}},
		},
	}
	c := NoEndpointsClassifier{}
	got := c.Classify(results)
	if len(got) != 2 {
		t.Errorf("expected 2 findings for normal services, got %d", len(got))
	}
}

func TestNoEndpointsClassifier(t *testing.T) {
	tests := []struct {
		name        string
		results     ScanResults
		wantLen     int
		wantPodName string
	}{
		{
			name:    "empty input",
			results: ScanResults{},
			wantLen: 0,
		},
		{
			name: "single service with no endpoints",
			results: ScanResults{
				EnvName:    "prod",
				ClusterCtx: "prod-us-east",
				Services: []kube.ServiceIssue{
					{
						Namespace:   "default",
						ServiceName: "api-svc",
						Selector:    map[string]string{"app": "api", "tier": "backend"},
					},
				},
			},
			wantLen:     1,
			wantPodName: "api-svc",
		},
		{
			name: "multiple services with no endpoints",
			results: ScanResults{
				Services: []kube.ServiceIssue{
					{Namespace: "ns1", ServiceName: "svc-a", Selector: map[string]string{"app": "a"}},
					{Namespace: "ns2", ServiceName: "svc-b", Selector: map[string]string{"app": "b"}},
				},
			},
			wantLen: 2,
		},
	}

	c := NoEndpointsClassifier{}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			got := c.Classify(tt.results)
			if len(got) != tt.wantLen {
				t.Fatalf("got %d findings, want %d", len(got), tt.wantLen)
			}
			if tt.wantLen == 0 {
				return
			}
			f := got[0]
			if f.Category != CategoryNoEndpoints {
				t.Errorf("category = %q, want %q", f.Category, CategoryNoEndpoints)
			}
			if f.Severity != SeverityWarning {
				t.Errorf("severity = %q, want %q", f.Severity, SeverityWarning)
			}
			if f.DetailFields["selector"] == "" {
				t.Error("DetailFields missing selector")
			}
			if tt.wantPodName != "" && f.PodName != tt.wantPodName {
				t.Errorf("PodName = %q, want %q", f.PodName, tt.wantPodName)
			}
		})
	}
}
